# Generated by Django 6.0.5 on 2026-07-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_subject',
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workspace_invite', 'Workspace Invite'), ('task_assigned', 'Task Assigned'), ('task_approved', 'Task Approved'), ('workspace_created', 'Workspace Created')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='accounts_no_status_586bbe_idx'),
        ),
    ]
