# Generated by Django 6.0.5 on 2026-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workspace_credit_balance_auditrecord_creditusage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('credit_balance__gte', 0)), name='credit_balance_non_negative'),
        ),
    ]
