# Generated by Django 6.0.5 on 2026-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
